export type AnalyzeInput={storeUrl:string;competitors?:string[]};
export type SiteSnapshot={url:string;title:string;description:string;h1:string[];h2:string[];text:string};
export function normalizeUrl(v:string){const x=v.trim();return /^https?:\/\//i.test(x)?x:`https://${x}`}
function hostname(u:string){try{return new URL(normalizeUrl(u)).hostname.replace(/^www\./,'').toLowerCase()}catch{return ''}}
function decodeHtml(h:string){return h.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<noscript[\s\S]*?<\/noscript>/gi,' ').replace(/<svg[\s\S]*?<\/svg>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/\s+/g,' ').trim()}
function extract(html:string,url:string):SiteSnapshot{const title=html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]?.trim()||'';const description=html.match(/<meta[^>]+(?:name|property)=["'](?:description|og:description)["'][^>]+content=["']([^"']*)["']/i)?.[1]?.trim()||'';const h1=[...html.matchAll(/<h1[^>]*>([\s\S]*?)<\/h1>/gi)].map(m=>decodeHtml(m[1]||'')).filter(Boolean).slice(0,8);const h2=[...html.matchAll(/<h2[^>]*>([\s\S]*?)<\/h2>/gi)].map(m=>decodeHtml(m[1]||'')).filter(Boolean).slice(0,15);return{url,title,description,h1,h2,text:decodeHtml(html).slice(0,16000)}}
export async function fetchSite(url:string){const normalized=normalizeUrl(url);const c=new AbortController();const t=setTimeout(()=>c.abort(),12000);try{const r=await fetch(normalized,{signal:c.signal,headers:{'User-Agent':'Mozilla/5.0 (compatible; COANTO/1.0)'}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return extract(await r.text(),normalized)}finally{clearTimeout(t)}}
function searchUrl(q:string){return `https://html.duckduckgo.com/html/?q=${encodeURIComponent(q)}`}
async function webSearch(q:string){const c=new AbortController();const t=setTimeout(()=>c.abort(),10000);try{const r=await fetch(searchUrl(q),{signal:c.signal,headers:{'User-Agent':'Mozilla/5.0'}});if(!r.ok)return[];const html=await r.text();const out:string[]=[];for(const m of html.matchAll(/<a[^>]+class=["'][^"']*result__a[^"']*["'][^>]+href=["']([^"']+)["']/gi)){try{const u=new URL(m[1].startsWith('//')?`https:${m[1]}`:m[1]);const target=u.searchParams.get('uddg')||u.href;if(/^https?:/i.test(target))out.push(target)}catch{}}return out}finally{clearTimeout(t)}}
function candidateDomains(urls:string[],own:string){const blocked=['duckduckgo.com','facebook.com','instagram.com','youtube.com','linkedin.com','x.com','twitter.com','pinterest.com','reddit.com','wikipedia.org','google.com','bing.com'];const seen=new Set<string>();const out:string[]=[];for(const u of urls){const h=hostname(u);if(!h||h===own||h.endsWith(`.${own}`)||blocked.some(b=>h===b||h.endsWith(`.${b}`))||seen.has(h))continue;seen.add(h);out.push(`https://${h}`);if(out.length>=20)break}return out}
function cleanBrandText(v:string){return v.replace(/\b(home|homepage|welcome|official|online|international|global|select your country|shop now|shop online)\b/gi,' ').replace(/[|•·–—:-]+/g,' ').replace(/\s+/g,' ').trim()}
function identityCandidates(main:SiteSnapshot){const raw=[main.title,...main.h1,...main.h2,main.description].map(cleanBrandText).filter(Boolean);const names:string[]=[];for(const s of raw){const parts=s.split(/\s+/).filter(Boolean);if(parts.length<=10)names.push(s);if(names.length>=6)break}return names}
function likelyBrand(main:SiteSnapshot){const h=hostname(main.url);const name=h.split('.')[0].replace(/[-_]+/g,' ');return name||identityCandidates(main)[0]||'business'}
export async function discoverCompetitors(main:SiteSnapshot,explicit:string[]=[]){
 const own=hostname(main.url);const brand=likelyBrand(main);const ids=identityCandidates(main);const queries=[
  `"${brand}" competitors`,
  `"${brand}" alternatives`,
  `"${brand}" vs competitors`,
  `${brand} competitors alternatives 2026`,
  `${ids[0]||brand} similar companies`,
  `${brand} market competitors`
 ];
 const found=(await Promise.all(queries.map(webSearch))).flat();
 const candidates=candidateDomains([...explicit,...found],own);
 const sites:SiteSnapshot[]=[];
 for(const u of candidates){try{const site=await fetchSite(u);const content=`${site.title} ${site.description} ${site.h1.join(' ')} ${site.h2.join(' ')} ${site.text.slice(0,5000)}`.toLowerCase();const generic=['search results','privacy policy','terms of service','login','sign in'];if(generic.every(x=>!content.includes(x))||site.h1.length>0)sites.push(site)}catch{}}
 return sites.slice(0,10)
}
export const ANALYSIS_SCHEMA=`Return JSON only: {"decisionPulse":{"threat":{"title":"","description":"","severity":"critical|high|medium|low"},"opportunity":{"title":"","description":"","strength":"high|medium|low"},"action":{"title":"","description":"","priority":"high|medium|low"}},"snapshot":{"competitorCount":0,"meaningfulSignals":0,"evidenceStrength":"high|medium|low","dataCompleteness":"high|medium|low"},"marketTrend":[],"signals":[{"id":"","competitor":"","type":"","title":"","detail":"","impact":"high|medium|low","observedAt":"","evidence":"","sourceUrl":""}],"competitors":[{"name":"","url":"","relevance":0,"impact":0,"threat":"high|medium|low","note":""}],"beforeAfter":[],"timeline":[],"impact":{"strategic":0,"market":0,"financialAvailable":false,"financialNote":""},"scenarios":[],"priorityMatrix":[],"actions":[],"trust":[],"unknowns":[]}`;
export function buildPrompt(main:SiteSnapshot,competitors:SiteSnapshot[]){return `You are COANTO. The PRIMARY SITE is only the user's baseline/context. The COMPETITOR SITES are the main subject. Competitors were discovered automatically from public search and then fetched for verification. Never treat the primary site as a competitor. Never invent competitors, prices, sales, revenue, market share, percentages, dates, or financial impact. Only list a competitor when its supplied evidence makes its business identity and relevance reasonably clear. Every competitor claim must be supported by supplied competitor evidence. Prefer 3-8 meaningful signals. If evidence is insufficient, say unknown rather than filling gaps. Arabic output. ${ANALYSIS_SCHEMA}\nPRIMARY BASELINE:\n${JSON.stringify(main)}\nDISCOVERED COMPETITORS:\n${JSON.stringify(competitors)}`}
export function parseJsonBlock(t:string){const a=t.indexOf('{'),b=t.lastIndexOf('}');if(a<0||b<0)throw new Error('النموذج لم يُعِد JSON صالحًا');return JSON.parse(t.slice(a,b+1))}
