import { createServerFn } from "@tanstack/react-start";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";

export type BusinessInsight={id:string;title:string;summary:string;category:string;impact:string;confidence:number;evidence:unknown[];recommendation:string|null;createdAt:string};
export type BusinessMetric={id:string;metricKey:string;metricValue:number;unit:string|null;periodStart:string|null;periodEnd:string|null;createdAt:string};
const mapInsight=(r:any):BusinessInsight=>({id:r.id,title:r.title,summary:r.summary,category:r.category,impact:r.impact,confidence:Number(r.confidence??0),evidence:Array.isArray(r.evidence)?r.evidence:[],recommendation:r.recommendation??null,createdAt:r.created_at});
const mapMetric=(r:any):BusinessMetric=>({id:r.id,metricKey:r.metric_key,metricValue:Number(r.metric_value),unit:r.unit??null,periodStart:r.period_start??null,periodEnd:r.period_end??null,createdAt:r.created_at});
export const listBusinessInsights=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).inputValidator((i:{limit?:number})=>i??{}).handler(async({data,context})=>{const limit=Math.min(Math.max(data.limit??50,1),100);const {data:rows,error}=await context.supabase.from("business_insights").select("id,title,summary,category,impact,confidence,evidence,recommendation,created_at").eq("user_id",context.userId).order("created_at",{ascending:false}).limit(limit);if(error)throw new Error(error.message);return(rows??[]).map(mapInsight);});
export const listBusinessMetrics=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).inputValidator((i:{limit?:number})=>i??{}).handler(async({data,context})=>{const limit=Math.min(Math.max(data.limit??100,1),200);const {data:rows,error}=await context.supabase.from("business_metrics").select("id,metric_key,metric_value,unit,period_start,period_end,created_at").eq("user_id",context.userId).order("created_at",{ascending:false}).limit(limit);if(error)throw new Error(error.message);return(rows??[]).map(mapMetric);});
export const saveBusinessInsight=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((i:{title:string;summary:string;category:string;impact?:string;confidence?:number;evidence?:unknown[];recommendation?:string;sourceAnalysisId?:string})=>i).handler(async({data,context})=>{const title=data.title.trim(),summary=data.summary.trim();if(!title||!summary)throw new Error("عنوان وملخص الرؤية مطلوبان");const confidence=Math.min(Math.max(data.confidence??0,0),1);const {data:row,error}=await context.supabase.from("business_insights").insert({user_id:context.userId,title,summary,category:data.category,impact:data.impact??"medium",confidence,evidence:data.evidence??[],recommendation:data.recommendation??null,source_analysis_id:data.sourceAnalysisId??null}).select("id,title,summary,category,impact,confidence,evidence,recommendation,created_at").single();if(error)throw new Error(error.message);return mapInsight(row);});
