import { fetchSite, hostname, normalizeUrl, searchEvidenceForUrl, validateTargetUrl, type SiteSnapshot } from './analyze.server';

type JsonRecord=Record<string,unknown>;
type GeminiCandidate={name:string;url:string;reason:string;category:string;commercialEvidence:string};
export type GeminiDiscoveryResult={snapshots:SiteSnapshot[];candidateCount:number;searchQueries:number;status:'ok'|'missing-key'|'provider-error'|'empty'};
function record(value:unknown):JsonRecord{return value&&typeof value==='object'?value as JsonRecord:{}}
function array(value:unknown):unknown[]{return Array.isArray(value)?value:[]}
function stringValue(value:unknown):string{return typeof value==='string'?value:''}
function parseJson(text:string){const cleaned=text.replace(/^\uFEFF/,'').replace(/^\s*```(?:json)?\s*/i,'').replace(/\s*```\s*$/i,'').trim(),start=cleaned.indexOf('{'),end=cleaned.lastIndexOf('}');if(start<0||end<=start)return{} as JsonRecord;try{return record(JSON.parse(cleaned.slice(start,end+1)))}catch{return{} as JsonRecord}}

const rejectedHosts=['facebook.com','instagram.com','youtube.com','linkedin.com','x.com','twitter.com','pinterest.com','reddit.com','wikipedia.org','google.com','bing.com','duckduckgo.com','tiktok.com','amazon.com','ebay.com','etsy.com','similarweb.com','statista.com','crunchbase.com'];
function rejectedHost(host:string){return rejectedHosts.some((blocked)=>host===blocked||host.endsWith(`.${blocked}`));}
function competitorCandidates(data:JsonRecord,ownHost:string){const out:GeminiCandidate[]=[];for(const raw of array(data['competitors'])){const item=record(raw);const name=stringValue(item['name']).trim(),url=stringValue(item['url']).trim(),reason=stringValue(item['reason']).trim(),category=stringValue(item['category']).trim(),commercialEvidence=stringValue(item['commercialEvidence']).trim();if(!name||!url||!reason||!commercialEvidence)continue;const validation=validateTargetUrl(url);if(!validation.ok||!validation.url)continue;const normalized=normalizeUrl(validation.url),host=hostname(normalized);if(!host||host===ownHost||host.endsWith(`.${ownHost}`)||rejectedHost(host))continue;if(!out.some((existing)=>hostname(existing.url)===host))out.push({name,url:normalized,reason,category,commercialEvidence});}return out.slice(0,6)}
function responseText(data:JsonRecord){const texts:string[]=[];for(const candidate of array(data['candidates'])){const content=record(record(candidate)['content']);for(const part of array(content['parts'])){const text=stringValue(record(part)['text']);if(text)texts.push(text)}}return texts.join('\n').trim()}
function searchCount(data:JsonRecord){let count=0;for(const candidate of array(data['candidates'])){const metadata=record(record(candidate)['groundingMetadata']);count+=array(metadata['webSearchQueries']).length}return count}
function groundingSources(data:JsonRecord){const urls:string[]=[];for(const candidate of array(data['candidates'])){const metadata=record(record(candidate)['groundingMetadata']);for(const chunk of array(metadata['groundingChunks'])){const web=record(record(chunk)['web']);const uri=stringValue(web['uri']).trim();if(/^https?:\/\//i.test(uri)&&!urls.includes(uri))urls.push(uri)}}return urls.slice(0,12)}
function discoveryModel(){return process.env['GEMINI_DISCOVERY_MODEL']?.trim()||'gemini-3.1-flash-lite'}
const schema={type:'OBJECT',properties:{competitors:{type:'ARRAY',items:{type:'OBJECT',properties:{name:{type:'STRING'},url:{type:'STRING'},reason:{type:'STRING'},category:{type:'STRING'},commercialEvidence:{type:'STRING'}},required:['name','url','reason','category','commercialEvidence']}}},required:['competitors']};

function groundedEvidence(candidate:GeminiCandidate,sources:string[]){return [`Gemini Google Search grounded competitor candidate: ${candidate.name} — ${candidate.reason}`,`Grounded category: ${candidate.category}`,`Grounded commercial evidence: ${candidate.commercialEvidence}`,...sources.slice(0,4).map((url)=>`Google Search grounding source: ${url}`)];}
function augmentSnapshot(site:SiteSnapshot,candidate:GeminiCandidate,sources:string[]):SiteSnapshot{const grounded=groundedEvidence(candidate,sources);return{...site,description:[site.description,candidate.reason].filter(Boolean).join(' '),text:`${site.text}\nGrounded category: ${candidate.category}. Grounded commercial evidence: ${candidate.commercialEvidence}. ${candidate.reason}`.slice(0,18000),evidence:[...site.evidence,...grounded]};}
function groundedSnapshot(candidate:GeminiCandidate,sources:string[]):SiteSnapshot{return{url:candidate.url,title:candidate.name,description:candidate.reason,h1:[candidate.name],h2:candidate.category?[candidate.category]:[],text:`Google Search grounded public evidence. ${candidate.name}. Category: ${candidate.category}. Commercial evidence: ${candidate.commercialEvidence}. ${candidate.reason}`.slice(0,12000),sourceType:'search-index',evidence:groundedEvidence(candidate,sources)};}

export async function discoverCompetitorsWithGemini(main:SiteSnapshot):Promise<GeminiDiscoveryResult>{
 const apiKey=process.env['GEMINI_API_KEY']?.trim();if(!apiKey)return{snapshots:[],candidateCount:0,searchQueries:0,status:'missing-key'};
 const model=discoveryModel(),ownHost=hostname(main.url);const context=[main.title,main.description,...main.h1,...main.h2,main.text.slice(0,4500)].filter(Boolean).join('\n').slice(0,6500);
 const prompt=`Use Google Search to identify up to 6 direct commercial competitors of ${main.url}. Determine the actual business/category from the observed target-site context below. Return only real companies with their canonical official homepage URLs. For every candidate provide: (1) why it directly competes, (2) a concise category, and (3) concrete public commercial evidence that it sells a substantially similar product/service to similar customers. Exclude articles, directories, comparison/review sites, social profiles, marketplaces, investors and data providers. Never invent a company, URL, or commercial fact. If evidence is weak, omit the candidate.\n\nTarget-site context:\n${context}`;
 const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),45_000);
 try{
  const response=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`,{method:'POST',signal:controller.signal,headers:{'Content-Type':'application/json','x-goog-api-key':apiKey},body:JSON.stringify({contents:[{role:'user',parts:[{text:prompt}]}],tools:[{google_search:{}}],generationConfig:{responseMimeType:'application/json',responseSchema:schema,temperature:0.1,maxOutputTokens:1800}})});
  if(!response.ok){const detail=(await response.text()).slice(0,500);console.error('Gemini competitor discovery failed',{model,status:response.status,detail});return{snapshots:[],candidateCount:0,searchQueries:0,status:'provider-error'}}
  const raw=record(await response.json()),text=responseText(raw),candidates=competitorCandidates(parseJson(text),ownHost),queries=searchCount(raw),sources=groundingSources(raw);
  const allowGroundedFallback=queries>0||sources.length>0;
  const settled=await Promise.all(candidates.map(async candidate=>{try{return augmentSnapshot(await fetchSite(candidate.url),candidate,sources)}catch{try{const indexed=await searchEvidenceForUrl(candidate.url);if(indexed)return augmentSnapshot(indexed,candidate,sources)}catch{}return allowGroundedFallback?groundedSnapshot(candidate,sources):null}}));
  const snapshots=settled.filter((x):x is SiteSnapshot=>Boolean(x));const result:GeminiDiscoveryResult={snapshots,candidateCount:candidates.length,searchQueries:queries,status:candidates.length?'ok':'empty'};
  console.info('Gemini competitor discovery',{model,status:result.status,candidates:candidates.length,verifiedSnapshots:snapshots.length,searchQueries:queries,groundingSources:sources.length,groundedFallbacks:snapshots.filter((site)=>site.evidence.some((item)=>item.startsWith('Gemini Google Search grounded competitor candidate:'))&&site.sourceType==='search-index').length,outputChars:text.length});return result;
 }catch(error){console.error('Gemini competitor discovery unavailable',{error});return{snapshots:[],candidateCount:0,searchQueries:0,status:'provider-error'}}finally{clearTimeout(timer)}
}
