import { createServerFn } from "@tanstack/react-start";
import { requireAuth } from "@/lib/auth-middleware";
import type { Json } from "@/integrations/supabase/types";

export type MemoryKind="decision"|"recommendation"|"insight"|"preference"|"note";
export type MemoryItem={id:string;kind:MemoryKind;title:string;content:Json;sourceAnalysisId:string|null;importance:number;createdAt:string;updatedAt:string};
const mapRow=(row:any):MemoryItem=>({id:row.id,kind:row.kind,title:row.title,content:row.content??{},sourceAnalysisId:row.source_analysis_id??null,importance:row.importance??50,createdAt:row.created_at,updatedAt:row.updated_at});
export const listMemory=createServerFn({method:"GET"}).middleware([requireAuth]).handler(async({context}):Promise<MemoryItem[]>=>{const {data,error}=await context.supabase.from("memory_items").select("id,kind,title,content,source_analysis_id,importance,created_at,updated_at").eq("user_id",context.userId).order("importance",{ascending:false}).order("created_at",{ascending:false}).limit(100);if(error)throw new Error(error.message);return(data??[]).map(mapRow);});
export const saveMemory=createServerFn({method:"POST"}).middleware([requireAuth]).inputValidator((input:{kind:MemoryKind;title:string;content?:Json;sourceAnalysisId?:string;importance?:number})=>input).handler(async({data,context}):Promise<MemoryItem>=>{const title=data.title.trim();if(!title)throw new Error("عنوان الذاكرة مطلوب");const importance=Math.max(0,Math.min(100,Math.round(data.importance??50)));const {data:row,error}=await context.supabase.from("memory_items").insert({user_id:context.userId,kind:data.kind,title,content:data.content??{},source_analysis_id:data.sourceAnalysisId??null,importance}).select("id,kind,title,content,source_analysis_id,importance,created_at,updated_at").single();if(error)throw new Error(error.message);return mapRow(row);});
export const deleteMemory=createServerFn({method:"POST"}).middleware([requireAuth]).inputValidator((input:{id:string})=>input).handler(async({data,context}):Promise<{deleted:boolean}>=>{const {error}=await context.supabase.from("memory_items").delete().eq("id",data.id).eq("user_id",context.userId);if(error)throw new Error(error.message);return{deleted:true};});
