import { createServerFn } from "@tanstack/react-start";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import type { Json } from "@/integrations/supabase/types";

export type MonitoringTarget={id:string;name:string;url:string;intervalHours:number;active:boolean;lastCheckedAt:string|null;nextCheckAt:string|null;createdAt:string};
export type MonitoringEvent={id:string;targetId:string;eventType:string;severity:string;title:string;summary:string;evidence:Json;detectedAt:string;acknowledgedAt:string|null};
const mapTarget=(r:any):MonitoringTarget=>({id:r.id,name:r.name,url:r.url,intervalHours:r.interval_hours,active:r.active,lastCheckedAt:r.last_checked_at,nextCheckAt:r.next_check_at,createdAt:r.created_at});
const mapEvent=(r:any):MonitoringEvent=>({id:r.id,targetId:r.target_id,eventType:r.event_type,severity:r.severity,title:r.title,summary:r.summary,evidence:r.evidence??{},detectedAt:r.detected_at,acknowledgedAt:r.acknowledged_at});
export const listMonitoringTargets=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).handler(async({context})=>{const {data,error}=await context.supabase.from("monitoring_targets").select("id,name,url,interval_hours,active,last_checked_at,next_check_at,created_at").eq("user_id",context.userId).order("created_at",{ascending:false});if(error)throw new Error(error.message);return(data??[]).map(mapTarget);});
export const createMonitoringTarget=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((i:{name:string;url:string;intervalHours?:number})=>i).handler(async({data,context})=>{const name=data.name.trim(),url=data.url.trim();if(!name||!url)throw new Error("اسم الموقع والرابط مطلوبان");const parsed=new URL(url);if(!["http:","https:"].includes(parsed.protocol))throw new Error("الرابط يجب أن يبدأ بـ http أو https");const hours=Math.min(Math.max(Math.round(data.intervalHours??24),1),720);const {data:row,error}=await context.supabase.from("monitoring_targets").insert({user_id:context.userId,name,url,interval_hours:hours,active:true,next_check_at:new Date(Date.now()+hours*3600000).toISOString()}).select("id,name,url,interval_hours,active,last_checked_at,next_check_at,created_at").single();if(error)throw new Error(error.message);return mapTarget(row);});
export const setMonitoringActive=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((i:{id:string;active:boolean})=>i).handler(async({data,context})=>{const {error}=await context.supabase.from("monitoring_targets").update({active:data.active}).eq("id",data.id).eq("user_id",context.userId);if(error)throw new Error(error.message);return{ok:true};});
export const listMonitoringEvents=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).inputValidator((i:{limit?:number})=>i??{}).handler(async({data,context})=>{const limit=Math.min(Math.max(data.limit??50,1),100);const {data:rows,error}=await context.supabase.from("monitoring_events").select("id,target_id,event_type,severity,title,summary,evidence,detected_at,acknowledged_at").eq("user_id",context.userId).order("detected_at",{ascending:false}).limit(limit);if(error)throw new Error(error.message);return(rows??[]).map(mapEvent);});
export const acknowledgeMonitoringEvent=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((i:{id:string})=>i).handler(async({data,context})=>{const {error}=await context.supabase.from("monitoring_events").update({acknowledged_at:new Date().toISOString()}).eq("id",data.id).eq("user_id",context.userId);if(error)throw new Error(error.message);return{ok:true};});
