import { createFileRoute } from "@tanstack/react-router";
import { ArrowUpLeft, CheckCircle2, Eye, ShieldCheck, Sparkles, Target, TrendingUp, AlertTriangle } from "lucide-react";
import type { ReactNode } from "react";

export const Route = createFileRoute("/demo")({
  component: DemoPage,
  head: () => ({
    meta: [
      { title: "COANTO — Demo" },
      { name: "description", content: "تجربة COANTO كمنصة ذكاء القرار التنافسي." },
    ],
  }),
});

const competitors = [
  { name: "Northstar Commerce", domain: "northstar.example", relevance: 94, impact: 88, threat: "high", note: "تشابه مرتفع في الفئة والعرض التجاري الظاهر." },
  { name: "Urban Market", domain: "urbanmarket.example", relevance: 86, impact: 76, threat: "medium", note: "يتنافس على نفس نية الشراء مع عرض أوسع." },
  { name: "Peak Supply", domain: "peaksupply.example", relevance: 78, impact: 71, threat: "medium", note: "منافس متخصص؛ قوته في وضوح العرض وسرعة التنفيذ." },
];

const signals = [
  ["توسيع العرض", "Northstar Commerce", "المنافس يعرض فئات إضافية حول المنتج الأساسي.", "high"],
  ["وضوح القيمة", "Urban Market", "الرسالة التجارية أكثر مباشرة في صفحات الهبوط.", "medium"],
  ["سرعة القرار", "Peak Supply", "رحلة الشراء المختصرة تقلل الاحتكاك قبل الدفع.", "medium"],
];

function DemoPage() {
  return <div dir="rtl" className="min-h-screen bg-[#070b11] text-[#f4f7fb]">
    <header className="sticky top-0 z-20 border-b border-white/[0.07] bg-[#080d15]/90 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><a href="/" className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#25cdb8]/10 text-[#25cdb8]"><Target size={18}/></div><div><div className="text-sm font-black tracking-[4px] text-[#25cdb8]">COANTO</div><div className="text-[10px] text-slate-500">EVIDENCE → INTELLIGENCE → DECISION</div></div></a><div className="flex gap-2"><a href="/history" className="rounded-xl border border-white/10 px-4 py-2 text-xs font-bold text-slate-300">الذاكرة</a><a href="/" className="rounded-xl bg-[#25cdb8] px-4 py-2 text-xs font-black text-[#04110e]">تحليل جديد</a></div></div></header>
    <main className="mx-auto max-w-7xl space-y-6 px-5 py-8">
      <section className="rounded-[28px] border border-[#1d3344] bg-[radial-gradient(circle_at_80%_0%,rgba(37,205,184,.14),transparent_35%),#0b121b] p-7 md:p-10"><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="flex items-center gap-2 text-[11px] font-black tracking-[2px] text-[#25cdb8]"><Sparkles size={14}/> LIVE PRODUCT DEMO</div><h1 className="mt-4 text-3xl font-black md:text-5xl">من الدليل إلى القرار.</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-slate-400">هذه تجربة مكتفية ذاتيًا لرحلة COANTO الكاملة. البيانات أدناه موسومة كـ Demo وليست قياسات حقيقية عن شركة بعينها.</p></div><span className="rounded-full border border-[#25cdb8]/30 bg-[#25cdb8]/10 px-4 py-2 text-xs font-black text-[#25cdb8]">DEMO DATA</span></div></section>
      <section className="grid gap-3 md:grid-cols-4"><Stat label="المنافسون" value="3" icon={<Target size={17}/>}/><Stat label="الإشارات" value="6" icon={<TrendingUp size={17}/>}/><Stat label="الأدلة" value="14" icon={<Eye size={17}/>}/><Stat label="قوة الدليل" value="قوية" icon={<ShieldCheck size={17}/>}/></section>
      <section className="grid gap-4 md:grid-cols-3"><Pulse title="التهديد" data={{title:"اتساع عرض المنافس المباشر",description:"هناك ضغط تنافسي قابل للتصرف، لكنه لا يثبت خسارة حصة سوقية.",level:"high"}}/><Pulse title="الفرصة" data={{title:"التركيز على القيمة قبل توسيع الكتالوج",description:"أفضل استجابة هي جعل القيمة والتميّز أوضح في نقاط القرار الأساسية.",level:"medium"}}/><Pulse title="القرار التالي" data={{title:"اختبر صفحة قيمة واحدة خلال 7 أيام",description:"ابدأ بتجربة صغيرة قابلة للقياس بدل إعادة بناء العرض كاملًا.",level:"high"}}/></section>
      <section className="rounded-3xl border border-white/10 bg-[#0b121b] p-6"><SectionTitle title="المنافسون المكتشفون" subtitle="Evidence-gated competitor set"/><div className="grid gap-3 md:grid-cols-3">{competitors.map(c=><div key={c.name} className="rounded-2xl border border-white/[0.08] bg-[#090f17] p-4"><div className="flex items-start justify-between gap-2"><div><b>{c.name}</b><div className="mt-1 text-[11px] text-slate-600">{c.domain}</div></div><span className="rounded-full border border-orange-400/20 bg-orange-400/10 px-2 py-1 text-[10px] font-black text-orange-200">{c.threat}</span></div><p className="mt-3 text-xs leading-6 text-slate-400">{c.note}</p><Metric label="الصلة" value={c.relevance}/><Metric label="التأثير" value={c.impact}/></div>)}</div></section>
      <section className="rounded-3xl border border-white/10 bg-[#0b121b] p-6"><SectionTitle title="إشارات تستحق الانتباه" subtitle="Signals that can change a decision"/><div className="space-y-3">{signals.map(([title,source,detail,level])=><div key={title} className="flex gap-4 rounded-2xl border border-white/[0.07] bg-[#090f17] p-4"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-[#25cdb8]/10 text-[#25cdb8]"><TrendingUp size={17}/></div><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><b className="text-sm">{title}</b><span className="text-[10px] text-slate-600">{source}</span><span className="rounded-full border border-amber-400/20 px-2 py-0.5 text-[10px] text-amber-200">{level}</span></div><p className="mt-1 text-xs leading-6 text-slate-400">{detail}</p><div className="mt-2 text-[10px] text-slate-600">الدليل: ملاحظة عامة قابلة للتتبع · Demo evidence</div></div></div>)}</div></section>
      <section className="grid gap-4 md:grid-cols-2"><Panel title="خريطة الأولوية"><div className="grid gap-2 sm:grid-cols-2"><Priority title="وضوح القيمة" impact="مرتفع" ease="سهل"/><Priority title="اختبار صفحة الهبوط" impact="مرتفع" ease="متوسط"/><Priority title="توسيع الكتالوج" impact="متوسط" ease="صعب"/><Priority title="مراقبة الأسعار" impact="متوسط" ease="سهل"/></div></Panel><Panel title="خطة العمل"><Action n="01" text="صياغة عرض قيمة أكثر حدة."/><Action n="02" text="إطلاق A/B test محدود لمدة 7 أيام."/><Action n="03" text="قياس التحويل قبل/بعد وربط النتيجة بالقرار."/></Panel></section>
      <section className="rounded-3xl border border-[#25cdb8]/15 bg-[#25cdb8]/[0.035] p-6"><div className="flex items-center gap-2 text-sm font-black text-[#25cdb8]"><ShieldCheck size={17}/> سلسلة الثقة</div><div className="mt-5 grid gap-3 md:grid-cols-4">{[["اكتشاف","بحث متعدد المصادر"],["تحقق","مباشر أو مفهرس"],["Evidence Gate","منع الادعاء غير المدعوم"],["Decision","توصية قابلة للتنفيذ"]].map(([a,b])=><div key={a} className="rounded-2xl border border-white/[0.07] bg-[#090f17] p-4"><CheckCircle2 size={17} className="text-[#25cdb8]"/><div className="mt-3 text-sm font-black">{a}</div><div className="mt-1 text-xs text-slate-500">{b}</div></div>)}</div><div className="mt-5 flex items-start gap-3 rounded-2xl border border-amber-400/15 bg-amber-400/[0.035] p-4 text-xs leading-6 text-amber-100/70"><AlertTriangle size={17} className="shrink-0 text-amber-300"/>الديمو يوضح تجربة المنتج فقط. لا تستخدم هذه الأرقام كحقائق سوقية؛ التحليل الحقيقي يولّد أدلة حية ويُظهر ما هو معلوم وما هو غير معلوم.</div></section>
    </main>
  </div>;
}
function Stat({label,value,icon}:{label:string;value:string;icon:ReactNode}){return <div className="rounded-2xl border border-white/10 bg-[#0b121b] p-4"><div className="flex items-center gap-2 text-xs text-slate-500">{icon}{label}</div><div className="mt-2 text-3xl font-black">{value}</div></div>}
function Pulse({title,data}:{title:string;data:{title:string;description:string;level:string}}){return <div className="rounded-3xl border border-white/10 bg-[#0b121b] p-5"><div className="flex justify-between text-xs font-black text-slate-400"><span>{title}</span><span className="rounded-full border border-white/10 px-2 py-1 text-[10px]">{data.level}</span></div><div className="mt-4 text-lg font-black">{data.title}</div><p className="mt-2 text-sm leading-7 text-slate-400">{data.description}</p></div>}
function Metric({label,value}:{label:string;value:number}){return <div className="mt-3"><div className="mb-1 flex justify-between text-[10px] text-slate-600"><span>{label}</span><span>{value}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-white/[0.06]"><div className="h-full rounded-full bg-[#25cdb8]" style={{width:`${value}%`}}/></div></div>}
function SectionTitle({title,subtitle}:{title:string;subtitle:string}){return <div className="mb-4"><h2 className="text-lg font-black">{title}</h2><p className="mt-1 text-xs text-slate-600">{subtitle}</p></div>}
function Panel({title,children}:{title:string;children:ReactNode}){return <section className="rounded-3xl border border-white/10 bg-[#0b121b] p-6"><h2 className="mb-4 text-lg font-black">{title}</h2>{children}</section>}
function Priority({title,impact,ease}:{title:string;impact:string;ease:string}){return <div className="rounded-2xl border border-white/[0.07] bg-[#090f17] p-4"><b className="text-sm">{title}</b><div className="mt-2 flex gap-2 text-[10px] text-slate-500"><span>Impact: {impact}</span><span>Ease: {ease}</span></div></div>}
function Action({n,text}:{n:string;text:string}){return <div className="flex gap-3 border-b border-white/[0.06] py-3 last:border-0"><span className="text-xs font-black text-[#25cdb8]">{n}</span><span className="text-sm text-slate-300">{text}</span></div>}
