import { createFileRoute } from '@tanstack/react-router';
import { Check, ShieldCheck, Sparkles } from 'lucide-react';

// @ts-expect-error TanStack route types are generated separately.
export const Route=createFileRoute('/pricing')({component:PricingPage});

const plans=[
  {name:'تجربة COANTO',tag:'متاح الآن',price:'بدون دفع',description:'جرّب جوهر Competitive Decision Intelligence أثناء مرحلة التحقق من المنتج.',features:['تحليل المنافسين بالأدلة','اكتشاف المنافسين','مراقبة وتغييرات موثقة','قرارات مرتبطة بالأدلة'],cta:'ابدأ التجربة',href:'/auth',featured:true},
  {name:'Free',tag:'طبقة دائمة',price:'$0',description:'وصول أساسي محدود يبقى متاحاً حتى بدون اشتراك مدفوع.',features:['وصول أساسي للمنصة','سجل التحليلات','استخدام ضمن حدود الكلفة','ترقية لاحقاً بدون فقدان البيانات'],cta:'ابدأ مجاناً',href:'/auth',featured:false},
  {name:'Starter',tag:'قريباً',price:'السعر عند الإطلاق',description:'للشركات التي تريد تشغيل المراقبة التنافسية بشكل مستمر وحدود أعلى.',features:['حدود استخدام أعلى','مراقبة أوسع','تنبيهات وتقارير دورية','سجل قرارات تنفيذي'],cta:'قريباً',href:'/pricing',featured:false},
  {name:'Pro',tag:'قريباً',price:'السعر عند الإطلاق',description:'للفرق التي تحتاج استخداماً مكثفاً وذكاءً تنافسياً أوسع.',features:['قدرات مراقبة موسعة','تقارير تنفيذية متقدمة','أولوية أعلى للعمليات المكلفة','جاهزية لتكاملات إضافية'],cta:'قريباً',href:'/pricing',featured:false},
];

function PricingPage(){return <div dir="rtl" className="min-h-screen bg-[#070b11] text-[#f4f7fb]"><header className="border-b border-white/[.07] bg-[#080d15]"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5"><a href="/" className="font-black tracking-[4px] text-[#25cdb8]">COANTO</a><div className="flex items-center gap-4 text-xs text-slate-400"><a href="/auth">دخول</a><a href="/billing">حسابي</a></div></div></header><main className="mx-auto max-w-6xl px-5 py-12"><section className="mx-auto max-w-3xl text-center"><div className="inline-flex items-center gap-2 rounded-full border border-[#25cdb8]/20 bg-[#25cdb8]/5 px-3 py-2 text-xs font-bold text-[#25cdb8]"><Sparkles size={14}/> PRICING VALIDATION</div><h1 className="mt-5 text-4xl font-black md:text-5xl">ابدأ بالقيمة أولاً، والدفع يأتي بعد إثباتها.</h1><p className="mx-auto mt-4 max-w-2xl text-sm leading-7 text-slate-400">COANTO في مرحلة التحقق التجاري. لذلك لا نفرض سعراً مصطنعاً قبل تثبيت القيمة والسوق. بنية الاشتراكات جاهزة، والأسعار المدفوعة ستُثبت عند تفعيل مزود الدفع المناسب.</p></section><section className="mt-10 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{plans.map(plan=><article key={plan.name} className={`rounded-3xl border p-6 ${plan.featured?'border-[#25cdb8]/40 bg-[#0d1a1c]':'border-white/10 bg-[#0b121b]'}`}><div className="flex items-center justify-between gap-3"><h2 className="text-xl font-black">{plan.name}</h2><span className="rounded-full bg-white/5 px-2 py-1 text-[10px] text-slate-400">{plan.tag}</span></div><div className="mt-5 text-2xl font-black text-[#25cdb8]">{plan.price}</div><p className="mt-3 min-h-20 text-xs leading-6 text-slate-500">{plan.description}</p><div className="mt-5 space-y-3">{plan.features.map(feature=><div key={feature} className="flex items-start gap-2 text-xs text-slate-300"><Check size={14} className="mt-0.5 shrink-0 text-[#25cdb8]"/>{feature}</div>)}</div><a href={plan.href} className={`mt-6 block rounded-xl px-4 py-3 text-center text-xs font-black ${plan.featured?'bg-[#25cdb8] text-[#04110e]':'border border-white/10 text-slate-300'}`}>{plan.cta}</a></article>)}</section><section className="mt-8 flex items-start gap-3 rounded-2xl border border-white/10 bg-[#0b121b] p-5 text-xs leading-6 text-slate-400"><ShieldCheck size={18} className="mt-1 shrink-0 text-[#25cdb8]"/><div><b className="text-slate-200">الدفع مفصول عن المنتج تقنياً.</b> حالة الاشتراك والصلاحيات محفوظة داخل COANTO، بينما مزود الدفع سيكون طبقة قابلة للاستبدال. هذا يمنع ربط المنصة بمزود واحد من البداية.</div></section></main></div>}
