import { useMemo, useState } from 'react';
import { Loader2, Radar, ExternalLink, X, Eye, Zap } from 'lucide-react';

type Signal={id:string;title:string;kind:string;platform:string;signalStrength:string;freshness:string;state:string;whatHappened:string;businessFit:string;recommendedAction:string;triggerToWatch:string;evidenceSummary?:string};
type Source={title:string;url:string};
type Result={generatedAt:string;summary:string;trends:Signal[];sources:Source[];trustNote:string};

export default function CoantoPulseFast(){
 const [business,setBusiness]=useState(''); const [result,setResult]=useState<Result|null>(null); const [active,setActive]=useState<Signal|null>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
 const signals=useMemo(()=>result?.trends||[],[result]);
 async function scan(){
  if(!business.trim()){setError('اكتب نشاطك أو اهتماماتك أولًا.');return}
  setLoading(true);setError('');setActive(null);
  try{const r=await fetch('/api/trends-pulse',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mode:'discover',profile:{businessName:business,productDescription:business,region:'السعودية',city:'',audience:'',dialect:'عربي',tone:'واضح',objective:'اكتشاف ما يهمني',platforms:['TikTok','Instagram Reels','YouTube','X','Google/Web']}})});const d=await r.json();if(!r.ok)throw new Error(d?.error||'تعذّر تشغيل الرصد');setResult(d.result);setActive(d.result?.trends?.[0]||null)}catch(e){setError(e instanceof Error?e.message:'تعذّر تشغيل الرصد')}finally{setLoading(false)}
 }
 return <main dir="rtl" className="min-h-screen bg-[#05080d] text-white">
  <header className="border-b border-white/10 bg-black/30"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4"><div><b className="tracking-[.2em]">COANTO</b><div className="text-xs text-slate-500">كوانتو يرى ما يتحرك قبل أن تضيع وقتك بالبحث</div></div><div className="flex items-center gap-2 text-xs text-emerald-300"><span className="h-2 w-2 animate-pulse rounded-full bg-emerald-300"/>LIVE RADAR</div></div></header>
  <div className="mx-auto max-w-7xl px-4 py-8">
   <section className="grid gap-5 lg:grid-cols-[.7fr_1.3fr]">
    <div className="rounded-[28px] border border-white/10 bg-white/[.035] p-6"><div className="mb-3 flex items-center gap-2 text-cyan-300"><Radar size={18}/> رادارك الشخصي</div><h1 className="text-3xl font-black leading-tight">لا تفتّش عن اللي عم يتحرك.<br/><span className="text-cyan-300">خلّي كوانتو يجيبه لعندك.</span></h1><p className="mt-3 text-sm leading-6 text-slate-400">اكتب نشاطك أو اهتماماتك. كوانتو يبحث حيًا ويعرض فقط الإشارات التي تستحق انتباهك.</p><textarea value={business} onChange={e=>setBusiness(e.target.value)} placeholder="مثال: أنا صانع محتوى عن الذكاء الاصطناعي في الخليج…" className="mt-5 min-h-24 w-full rounded-2xl border border-white/10 bg-black/30 p-4 text-sm outline-none focus:border-cyan-300/40"/><button onClick={scan} disabled={loading} className="mt-3 flex w-full items-center justify-center gap-2 rounded-2xl bg-cyan-300 px-4 py-3 font-black text-slate-950 disabled:opacity-50">{loading?<><Loader2 className="animate-spin" size={17}/> عم نرصد الآن…</>:<><Radar size={17}/> شغّل الرادار الحقيقي</>}</button>{error&&<div className="mt-3 rounded-xl border border-rose-400/20 bg-rose-400/10 p-3 text-xs text-rose-100">{error}</div>}</div>
    <PulseLine signals={signals} active={active} setActive={setActive} loading={loading}/>
   </section>
   {result&&<><div className="mt-5 rounded-2xl border border-white/10 bg-white/[.025] p-4 text-sm text-slate-300"><b className="text-white">خلاصة كوانتو:</b> {result.summary}</div><section className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{signals.map((s,i)=><button key={s.id||i} onClick={()=>setActive(s)} className="rounded-2xl border border-white/10 bg-white/[.03] p-4 text-right transition hover:-translate-y-1 hover:border-cyan-300/30"><div className="flex items-center justify-between"><span className="text-[11px] text-cyan-300">{s.kind} · {s.platform}</span><State state={s.state}/></div><h3 className="mt-3 font-black">{s.title}</h3><p className="mt-2 line-clamp-2 text-xs leading-6 text-slate-400">{s.businessFit}</p><div className="mt-3 text-[11px] text-slate-500">اضغط لتفهم لماذا ←</div></button>)}</section></>}
  </div>
  {active&&<Detail signal={active} sources={result?.sources||[]} close={()=>setActive(null)}/>} 
 </main>
}
function PulseLine({signals,active,setActive,loading}:{signals:Signal[];active:Signal|null;setActive:(s:Signal)=>void;loading:boolean}){return <div className="relative min-h-[390px] overflow-hidden rounded-[28px] border border-white/10 bg-gradient-to-br from-sky-950/30 via-[#07111c] to-amber-950/20 p-5"><div className="flex items-center justify-between"><div><b>Pulse Line</b><div className="text-[11px] text-slate-500">الأقدم ← هذا الأسبوع ← أمس ← اليوم ← الآن</div></div><div className="text-xs text-slate-500">{signals.length?`${signals.length} إشارات`:'بانتظار الرصد'}</div></div><div className="absolute inset-x-8 top-[58%] h-px bg-gradient-to-r from-white/5 via-cyan-300/40 to-emerald-300/70"/><div className="absolute inset-x-8 top-[58%] h-16 -translate-y-8 bg-cyan-300/[.03] blur-xl"/>{loading&&<div className="absolute inset-0 grid place-items-center bg-[#05080d]/55 backdrop-blur-sm"><div className="text-center"><Radar className="mx-auto animate-pulse text-cyan-300" size={42}/><div className="mt-3 text-sm">كوانتو يمسح المصادر الآن…</div></div></div>}{!loading&&!signals.length&&<div className="absolute inset-0 grid place-items-center"><div className="max-w-xs text-center text-sm leading-7 text-slate-500">بعد أول رصد، الإشارات الحقيقية تظهر هنا على الزمن. الجديد أكبر، والقديم يصغر ويبهت.</div></div>}<div className="absolute inset-x-8 top-[58%] flex -translate-y-1/2 flex-row-reverse items-center justify-between">{signals.slice(0,7).map((s,i)=>{const size=Math.max(34,72-i*6);return <button key={s.id||i} onMouseEnter={()=>setActive(s)} onClick={()=>setActive(s)} title={s.title} style={{width:size,height:size,opacity:Math.max(.35,1-i*.1)}} className={`group relative grid shrink-0 place-items-center rounded-full border transition hover:scale-125 ${active?.id===s.id?'border-cyan-200 bg-cyan-300/30 shadow-[0_0_35px_rgba(103,232,249,.3)]':'border-white/20 bg-white/10'}`}><Zap size={Math.max(13,size/3)} /><span className="absolute top-full mt-2 w-24 truncate text-[10px] text-slate-400 group-hover:text-white">{s.title}</span></button>})}</div><div className="absolute bottom-4 left-5 right-5 flex justify-between text-[10px] text-slate-600"><span>قديم / يبرد</span><span>الآن / جديد</span></div></div>}
function State({state}:{state:string}){const c=state==='استخدم الآن'?'text-emerald-300':state==='راقب'?'text-amber-300':'text-slate-500';return <span className={`text-[10px] font-bold ${c}`}>{state}</span>}
function Detail({signal,sources,close}:{signal:Signal;sources:Source[];close:()=>void}){return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/70 p-3 backdrop-blur-sm md:items-center" onClick={close}><div onClick={e=>e.stopPropagation()} className="max-h-[88vh] w-full max-w-2xl overflow-auto rounded-[28px] border border-white/10 bg-[#0a111b] p-6"><div className="flex justify-between"><div><div className="text-xs text-cyan-300">{signal.kind} · {signal.platform}</div><h2 className="mt-2 text-2xl font-black">{signal.title}</h2></div><button onClick={close}><X/></button></div><Block title="شو صار؟" text={signal.whatHappened}/><Block title="ليش يهمك أنت؟" text={signal.businessFit}/><Block title="شو تعمل هلأ؟" text={signal.recommendedAction}/><Block title="شو نراقب بعد؟" text={signal.triggerToWatch}/>{signal.evidenceSummary&&<Block title="الدليل" text={signal.evidenceSummary}/>}<div className="mt-5 border-t border-white/10 pt-4"><div className="mb-2 flex items-center gap-2 text-xs text-slate-400"><Eye size={14}/> المصادر التي استخدمها الرصد</div>{sources.slice(0,5).map((s,i)=><a key={i} href={s.url} target="_blank" rel="noreferrer" className="mb-2 flex items-center justify-between rounded-xl border border-white/8 bg-white/[.03] p-3 text-xs hover:border-cyan-300/30"><span className="truncate">{s.title}</span><ExternalLink size={13}/></a>)}</div></div></div>}
function Block({title,text}:{title:string;text:string}){return <div className="mt-5"><div className="text-xs font-black text-slate-500">{title}</div><p className="mt-1 text-sm leading-7 text-slate-200">{text||'—'}</p></div>}
