/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as BusinessIntelligenceRouteImport } from './routes/business-intelligence'
import { Route as CompetitorsRouteImport } from './routes/competitors'
import { Route as DecisionRouteImport } from './routes/decision'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as NextRouteImport } from './routes/next'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ApiAnalyzeRouteImport } from './routes/api/analyze'
import { Route as ApiAuthRouteImport } from './routes/api/auth'
import { Route as ApiBusinessContextRouteImport } from './routes/api/business-context'
import { Route as ApiCompetitorsRouteImport } from './routes/api/competitors'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiMonitoringCronRouteImport } from './routes/api/monitoring-cron'
import { Route as ApiReadyRouteImport } from './routes/api/ready'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessIntelligenceRoute = BusinessIntelligenceRouteImport.update({
  id: '/business-intelligence',
  path: '/business-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitorsRoute = CompetitorsRouteImport.update({
  id: '/competitors',
  path: '/competitors',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionRoute = DecisionRouteImport.update({
  id: '/decision',
  path: '/decision',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const NextRoute = NextRouteImport.update({
  id: '/next',
  path: '/next',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeRoute = ApiAnalyzeRouteImport.update({
  id: '/api/analyze',
  path: '/api/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBusinessContextRoute = ApiBusinessContextRouteImport.update({
  id: '/api/business-context',
  path: '/api/business-context',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompetitorsRoute = ApiCompetitorsRouteImport.update({
  id: '/api/competitors',
  path: '/api/competitors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMonitoringCronRoute = ApiMonitoringCronRouteImport.update({
  id: '/api/monitoring-cron',
  path: '/api/monitoring-cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReadyRoute = ApiReadyRouteImport.update({
  id: '/api/ready',
  path: '/api/ready',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analysis': typeof AnalysisRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/business-intelligence': typeof BusinessIntelligenceRoute
  '/competitors': typeof CompetitorsRoute
  '/decision': typeof DecisionRoute
  '/demo': typeof DemoRoute
  '/history': typeof HistoryRoute
  '/memory': typeof MemoryRoute
  '/monitoring': typeof MonitoringRoute
  '/next': typeof NextRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/reports': typeof ReportsRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/business-context': typeof ApiBusinessContextRoute
  '/api/competitors': typeof ApiCompetitorsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/monitoring-cron': typeof ApiMonitoringCronRoute
  '/api/ready': typeof ApiReadyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analysis': typeof AnalysisRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/business-intelligence': typeof BusinessIntelligenceRoute
  '/competitors': typeof CompetitorsRoute
  '/decision': typeof DecisionRoute
  '/demo': typeof DemoRoute
  '/history': typeof HistoryRoute
  '/memory': typeof MemoryRoute
  '/monitoring': typeof MonitoringRoute
  '/next': typeof NextRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/reports': typeof ReportsRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/business-context': typeof ApiBusinessContextRoute
  '/api/competitors': typeof ApiCompetitorsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/monitoring-cron': typeof ApiMonitoringCronRoute
  '/api/ready': typeof ApiReadyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analysis': typeof AnalysisRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/business-intelligence': typeof BusinessIntelligenceRoute
  '/competitors': typeof CompetitorsRoute
  '/decision': typeof DecisionRoute
  '/demo': typeof DemoRoute
  '/history': typeof HistoryRoute
  '/memory': typeof MemoryRoute
  '/monitoring': typeof MonitoringRoute
  '/next': typeof NextRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/reports': typeof ReportsRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/business-context': typeof ApiBusinessContextRoute
  '/api/competitors': typeof ApiCompetitorsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/monitoring-cron': typeof ApiMonitoringCronRoute
  '/api/ready': typeof ApiReadyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/analysis'
    | '/auth'
    | '/billing'
    | '/business-intelligence'
    | '/competitors'
    | '/decision'
    | '/demo'
    | '/history'
    | '/memory'
    | '/monitoring'
    | '/next'
    | '/onboarding'
    | '/pricing'
    | '/reports'
    | '/api/analyze'
    | '/api/auth'
    | '/api/business-context'
    | '/api/competitors'
    | '/api/health'
    | '/api/monitoring-cron'
    | '/api/ready'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/analysis'
    | '/auth'
    | '/billing'
    | '/business-intelligence'
    | '/competitors'
    | '/decision'
    | '/demo'
    | '/history'
    | '/memory'
    | '/monitoring'
    | '/next'
    | '/onboarding'
    | '/pricing'
    | '/reports'
    | '/api/analyze'
    | '/api/auth'
    | '/api/business-context'
    | '/api/competitors'
    | '/api/health'
    | '/api/monitoring-cron'
    | '/api/ready'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/analysis'
    | '/auth'
    | '/billing'
    | '/business-intelligence'
    | '/competitors'
    | '/decision'
    | '/demo'
    | '/history'
    | '/memory'
    | '/monitoring'
    | '/next'
    | '/onboarding'
    | '/pricing'
    | '/reports'
    | '/api/analyze'
    | '/api/auth'
    | '/api/business-context'
    | '/api/competitors'
    | '/api/health'
    | '/api/monitoring-cron'
    | '/api/ready'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AnalysisRoute: typeof AnalysisRoute
  AuthRoute: typeof AuthRoute
  BillingRoute: typeof BillingRoute
  BusinessIntelligenceRoute: typeof BusinessIntelligenceRoute
  CompetitorsRoute: typeof CompetitorsRoute
  DecisionRoute: typeof DecisionRoute
  DemoRoute: typeof DemoRoute
  HistoryRoute: typeof HistoryRoute
  MemoryRoute: typeof MemoryRoute
  MonitoringRoute: typeof MonitoringRoute
  NextRoute: typeof NextRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  ReportsRoute: typeof ReportsRoute
  ApiAnalyzeRoute: typeof ApiAnalyzeRoute
  ApiAuthRoute: typeof ApiAuthRoute
  ApiBusinessContextRoute: typeof ApiBusinessContextRoute
  ApiCompetitorsRoute: typeof ApiCompetitorsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiMonitoringCronRoute: typeof ApiMonitoringCronRoute
  ApiReadyRoute: typeof ApiReadyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-intelligence': {
      id: '/business-intelligence'
      path: '/business-intelligence'
      fullPath: '/business-intelligence'
      preLoaderRoute: typeof BusinessIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitors': {
      id: '/competitors'
      path: '/competitors'
      fullPath: '/competitors'
      preLoaderRoute: typeof CompetitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decision': {
      id: '/decision'
      path: '/decision'
      fullPath: '/decision'
      preLoaderRoute: typeof DecisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/next': {
      id: '/next'
      path: '/next'
      fullPath: '/next'
      preLoaderRoute: typeof NextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze': {
      id: '/api/analyze'
      path: '/api/analyze'
      fullPath: '/api/analyze'
      preLoaderRoute: typeof ApiAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/business-context': {
      id: '/api/business-context'
      path: '/api/business-context'
      fullPath: '/api/business-context'
      preLoaderRoute: typeof ApiBusinessContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/competitors': {
      id: '/api/competitors'
      path: '/api/competitors'
      fullPath: '/api/competitors'
      preLoaderRoute: typeof ApiCompetitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/monitoring-cron': {
      id: '/api/monitoring-cron'
      path: '/api/monitoring-cron'
      fullPath: '/api/monitoring-cron'
      preLoaderRoute: typeof ApiMonitoringCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ready': {
      id: '/api/ready'
      path: '/api/ready'
      fullPath: '/api/ready'
      preLoaderRoute: typeof ApiReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AnalysisRoute: AnalysisRoute,
  AuthRoute: AuthRoute,
  BillingRoute: BillingRoute,
  BusinessIntelligenceRoute: BusinessIntelligenceRoute,
  CompetitorsRoute: CompetitorsRoute,
  DecisionRoute: DecisionRoute,
  DemoRoute: DemoRoute,
  HistoryRoute: HistoryRoute,
  MemoryRoute: MemoryRoute,
  MonitoringRoute: MonitoringRoute,
  NextRoute: NextRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  ReportsRoute: ReportsRoute,
  ApiAnalyzeRoute: ApiAnalyzeRoute,
  ApiAuthRoute: ApiAuthRoute,
  ApiBusinessContextRoute: ApiBusinessContextRoute,
  ApiCompetitorsRoute: ApiCompetitorsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiMonitoringCronRoute: ApiMonitoringCronRoute,
  ApiReadyRoute: ApiReadyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
